---
title: "Політологія."
documentclass: "extreport"
classoption:
  - "utf8"
  - "14pt"
author: "Ліневич А.С"
date: \today{}
toc: True
toc-depth: 5
lang: uk
geometry: [top=2cm, right=1cm, left=3cm, bottom=2cm]
header-includes:
    - \usepackage{xecyr}
    - \newfontfamily\cyrillicfont{Times New Roman}
    - \parindent=1.2cm
    - \usepackage{setspace}
    - \setstretch{1.3}

---
