---
title: "Соціологія."
documentclass: "extreport"
classoption:
  - "utf8"
  - "14pt"
  - "a4paper"
author: "Ліневич А.С"
date: \today{}
toc: True
toc-depth: 5
lang: uk
geometry: [top=2cm, right=1cm, left=3cm, bottom=2cm]
header-includes:
    - \usepackage{xecyr}
    - \newfontfamily\cyrillicfont{Times New Roman}
    - \usepackage{setspace}
    - \usepackage{indentfirst} 
    - \setstretch{1.3}
---
